version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

formats:
  - pdf
  - htmlzip

python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - requirements: requirements-optional.txt
